"""artist_contract and artistrelease_royalty_pct

Revision ID: 170c117f21d8
Revises: 144593803f2e
Create Date: 2026-04-18 16:29:14.689421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170c117f21d8'
down_revision = '144593803f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('royalty_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artist_contract', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_contract_artist_id'), ['artist_id'], unique=False)

    with op.batch_alter_table('artist_release', schema=None) as batch_op:
        batch_op.add_column(sa.Column('royalty_percentage', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist_release', schema=None) as batch_op:
        batch_op.drop_column('royalty_percentage')

    with op.batch_alter_table('artist_contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_contract_artist_id'))

    op.drop_table('artist_contract')
    # ### end Alembic commands ###
