"""phase4_streaming_royalties

Revision ID: 2ab2087b8792
Revises: a1b2c3d4e5f6
Create Date: 2026-04-17 15:20:41.916727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab2087b8792'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streaming_import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reporting_month', sa.Date(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=80), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=True),
    sa.Column('rows_aggregated', sa.Integer(), nullable=True),
    sa.Column('rows_skipped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('streaming_import', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streaming_import_reporting_month'), ['reporting_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_streaming_import_status'), ['status'], unique=False)

    op.create_table('artist_royalty_split',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isrc', sa.String(length=20), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isrc', 'artist_name', name='uq_artist_royalty_split')
    )
    with op.batch_alter_table('artist_royalty_split', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_royalty_split_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_royalty_split_isrc'), ['isrc'], unique=False)

    op.create_table('streaming_royalty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('isrc', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('sales_type', sa.String(length=50), nullable=False),
    sa.Column('reporting_month', sa.Date(), nullable=False),
    sa.Column('sales_month', sa.Date(), nullable=False),
    sa.Column('artist_name_csv', sa.String(length=255), nullable=True),
    sa.Column('track_title_csv', sa.String(length=255), nullable=True),
    sa.Column('label_name', sa.String(length=255), nullable=True),
    sa.Column('release_title', sa.String(length=255), nullable=True),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('streaming_sub_type', sa.String(length=50), nullable=True),
    sa.Column('release_type', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('total_quantity', sa.BigInteger(), nullable=True),
    sa.Column('total_gross_revenue', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('total_net_revenue', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('total_mechanical_fee', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['streaming_import.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'isrc', 'platform', 'country', 'sales_type', 'reporting_month', 'sales_month', name='uq_streaming_royalty_agg_key')
    )
    with op.batch_alter_table('streaming_royalty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streaming_royalty_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_streaming_royalty_isrc'), ['isrc'], unique=False)
        batch_op.create_index(batch_op.f('ix_streaming_royalty_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_streaming_royalty_reporting_month'), ['reporting_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_streaming_royalty_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('streaming_royalty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streaming_royalty_track_id'))
        batch_op.drop_index(batch_op.f('ix_streaming_royalty_reporting_month'))
        batch_op.drop_index(batch_op.f('ix_streaming_royalty_platform'))
        batch_op.drop_index(batch_op.f('ix_streaming_royalty_isrc'))
        batch_op.drop_index(batch_op.f('ix_streaming_royalty_import_id'))

    op.drop_table('streaming_royalty')
    with op.batch_alter_table('artist_royalty_split', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_royalty_split_isrc'))
        batch_op.drop_index(batch_op.f('ix_artist_royalty_split_artist_id'))

    op.drop_table('artist_royalty_split')
    with op.batch_alter_table('streaming_import', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streaming_import_status'))
        batch_op.drop_index(batch_op.f('ix_streaming_import_reporting_month'))

    op.drop_table('streaming_import')
    # ### end Alembic commands ###
