"""phase2 release track trackwork

Revision ID: cd28d5b2b218
Revises: d3f4682903a1
Create Date: 2026-04-04 00:06:12.518137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd28d5b2b218'
down_revision = 'd3f4682903a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('artists', sa.Text(), nullable=True),
    sa.Column('num_tracks', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('distributor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('primary_title', sa.String(length=255), nullable=False),
    sa.Column('recording_title', sa.String(length=255), nullable=True),
    sa.Column('aka_title', sa.String(length=255), nullable=True),
    sa.Column('aka_type_code', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=10), nullable=True),
    sa.Column('isrc', sa.String(length=20), nullable=True),
    sa.Column('track_label', sa.String(length=255), nullable=True),
    sa.Column('track_p_line', sa.String(length=255), nullable=True),
    sa.Column('artists', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('recording_date', sa.Date(), nullable=True),
    sa.Column('recording_engineer', sa.String(length=255), nullable=True),
    sa.Column('producer', sa.String(length=255), nullable=True),
    sa.Column('executive_producer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_work')
    op.drop_table('track')
    op.drop_table('release')
    # ### end Alembic commands ###
