"""initial migration

Revision ID: d3f4682903a1
Revises: 
Create Date: 2026-04-01 20:22:11.225873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f4682903a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writer', schema=None) as batch_op:
        batch_op.alter_column('default_publisher',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('default_publisher_ipi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writer', schema=None) as batch_op:
        batch_op.alter_column('default_publisher_ipi',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('default_publisher',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###
